jokes = {
            "clean": [
                "Why don’t skeletons fight each other? They don’t have the guts.",
                "I would tell you a joke about construction… but I’m still working on it.",
                "Why did the coffee file a police report? It got mugged.",
                "Why don’t eggs tell jokes? They’d crack each other up.",
                "Why did the scarecrow win an award? Because he was outstanding in his field.",
                "Why don’t scientists trust atoms? Because they make up everything.",
                "What do you call fake spaghetti? An impasta.",
                "Why did the bicycle fall over? It was two-tired.",
                "Why did the math book look sad? Because it had too many problems.",
                "What did one wall say to the other wall? I’ll meet you at the corner.",
                "Why can’t your nose be 12 inches long? Because then it would be a foot.",
                "What do you call cheese that isn’t yours? Nacho cheese.",
                "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
                "What do you call a bear with no teeth? A gummy bear.",
                "Why don’t some couples go to the gym? Because some relationships don’t work out.",
                "Why did the tomato turn red? Because it saw the salad dressing.",
                "Why do bees have sticky hair? Because they use honeycombs.",
                "Why don’t oysters donate to charity? Because they are shellfish.",
                "Why did the computer go to the doctor? It caught a virus.",
                "Why did the cookie go to the hospital? Because he felt crummy.",
                "Why did the mushroom go to the party alone? Because he’s a fungi.",
                "What did the zero say to the eight? Nice belt!",
                "Why did the banana go to the doctor? It wasn’t peeling well.",
                "Why did the student eat his homework? Because the teacher said it was a piece of cake.",
                "Why did the cow go to space? To see the moooon.",
                "Why don’t ants get sick? Because they have tiny ant-bodies.",
                "What do you call a sleeping bull? A bulldozer.",
                "Why did the orange stop? Because it ran out of juice.",
                "What do you call a fish with no eyes? Fsh.",
                "Why did the chicken join a band? Because it had the drumsticks.",
                "Why don’t vampires like garlic? Because it’s a pain in the neck.",
                "Why did the belt go to jail? Because it held up a pair of pants.",
                "Why did the picture go to jail? Because it was framed.",
                "Why did the stadium get hot after the game? Because all the fans left.",
                "Why did the broom get a promotion? Because it swept the competition.",
                "Why did the duck go to the doctor? Because it was feeling under the feather.",
                "Why did the snail paint an S on his car? So people would say, 'Look at that S-car-go!'",
                "Why did the pencil go to the principal’s office? It had a point to make.",
                "What do you call a group of musical whales? An orca-stra.",
                "Why was the math lecture so long? The professor kept going off on a tangent.",
                "Why did the calendar go to therapy? Its days were numbered.",
                "Why did the rope go to school? It wanted to be a knot-ledgeable rope.",
                "Why did the student bring a ladder to school? Because he wanted to go to high school.",
                "Why did the man put his money in the freezer? He wanted cold hard cash.",
                "Why was the computer tired when it got home? It had too many tabs open.",
                "Why did the tomato blush? Because it saw the salad dressing.",
                "Why did the cookie go to the principal’s office? It was caught crumbling under pressure.",
                "Why did the stadium get hot after the concert? Because all the fans left.",
                "Why did the student throw a clock out the window? He wanted to see time fly.",
                "Why was the music teacher locked out of her classroom? Her keys were on the piano.",
                "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
                "Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field and learned quickly.",
                "Why did the golfer bring an extra shirt? In case he got a hole in one.",
                "Why did the owl get a promotion? Because he was outstanding in his field.",
                "Why did the banana go to the party? Because it was a-peeling.",
                "Why did the frog take the bus to work? His car got toad away.",
                "Why did the ghost go into the bar? For the boos.",
                "Why did the cookie go to therapy? It felt crumby.",
                "Why did the tomato turn red? Because it saw the salad dressing.",
                "Why did the student eat his homework? Because the teacher said it was a piece of cake.",
                "Why don’t skeletons fight each other? They don’t have the guts.",
                "Why did the computer go to therapy? It had too many bytes.",
                "Why did the math book look sad? Because it had too many problems.",
                "Why did the stadium get hot? Because all the fans left.",
                "Why did the pencil cross the road? To get to the other line.",
                "Why did the music teacher need a ladder? To reach the high notes.",
                "Why did the coffee file a police report? It got mugged.",
                "Why did the bicycle fall over? It was two-tired.",
                "Why did the student eat a light bulb? He wanted to be bright.",
                "Why did the cookie cry? Because his mom was a wafer too long.",
                "Why did the cow go to space? To see the moooon.",
                "Why did the computer go to school? To improve its processing skills.",
                "Why did the tomato blush? Because it saw the salad dressing.",
                "Why did the mushroom get invited to parties? Because he’s a fungi.",
                "Why did the math teacher go to the beach? To work on her tan-gent.",
                "Why did the student bring a ruler to bed? To see how long he slept.",
                "Why did the grape stop in the middle of the road? It ran out of juice.",
                "Why did the scarecrow win an award? Because he was outstanding in his field.",
                "Why did the horse go behind the tree? To change his jockeys.",
                "Why did the belt go to jail? Because it held up a pair of pants.",
                "Why did the skeleton go to the party alone? Because he had no body to go with.",
                "Why did the chicken join a band? Because it had the drumsticks.",
                "Why did the frog call his insurance company? He had a jump in his car.",
                "Why did the grape stop in the middle of the street? It ran out of juice.",
                "Why did the owl invite his friends over? He wanted to have a hoot.",
                "Why did the broom get a promotion? Because it swept the competition.",
                "Why did the student bring a ladder to school? Because he wanted to go to high school.",
                "Why did the scarecrow get promoted? Because he was outstanding in his field.",
                "Why did the dog sit in the shade? He didn’t want to be a hot dog.",
                "Why did the tree go to the dentist? To get a root canal.",
                "Why did the fish blush? Because it saw the ocean’s bottom.",
                "Why did the bicycle fall over? Because it was two-tired.",
                "Why did the student eat his homework? Because the teacher said it was a piece of cake.",
                "Why did the stadium get hot after the game? Because all the fans left.",
                "Why did the pencil go to the principal’s office? It had a point to make.",
                "Why did the coffee go to the police? It got mugged.",
                "Why did the tomato turn red? Because it saw the salad dressing.",
                "Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field.",
                "Why did the mushroom go to the party alone? Because he’s a fungi.",
                "Why did the student bring a ladder to school? To go to high school."
            ],
            "dark": [
                "I have a stepladder because my real ladder left when I was a kid.",
                "Why don’t graveyards ever get overcrowded? People are dying to get in.",
                "I’m great at multitasking. I can waste time, be unproductive, and procrastinate all at once.",
                "The cemetery looks overcrowded. People must be dying to get in.",
                "Why don’t zombies eat clowns? Because they taste funny.",
                "I have a joke about suicide… but it kills the mood.",
                "Why did the old man fall in the well? Because he couldn’t see that well.",
                "My therapist says I have a preoccupation with vengeance. We’ll see about that.",
                "I’d tell you a joke about murder… but I might get arrested.",
                "The man who invented autocorrect should burn in hello.",
                "I have a stepladder… my real ladder ran away from home.",
                "Why don’t graveyards ever get overcrowded? Because people are dying to get in.",
                "I like my humor like I like my coffins: dark.",
                "I have a joke about a broken pencil… but it’s pointless.",
                "I know they say that money talks… but mine just waves goodbye.",
                "Why don’t cannibals eat comedians? They taste funny.",
                "My friend said he didn’t understand cloning… I said, 'That makes two of us.'",
                "I have a dark sense of humor… I see the glass as half empty and poisoned.",
                "Why do we tell actors to 'break a leg?' Because every play has a cast.",
                "I told my wife she was drawing her eyebrows too high… she looked surprised.",
                "Why don’t graveyards ever get overcrowded? People are dying to get in.",
                "I have a joke about amputees… but it’s a bit disarming.",
                "I used to play piano by ear… now I use my fingers, it’s safer.",
                "Why did the scarecrow win an award? Because he was outstanding in his field… and he had a dark side.",
                "I have a joke about depression… but it’s a little sad.",
                "The man who survived mustard gas and pepper spray is now a seasoned veteran.",
                "I’d tell a joke about necrophilia… but it’s a dead topic.",
                "Why did the man stare at the can of orange juice for hours? Because it said concentrate.",
                "I have a joke about insomnia… but I can’t sleep on it.",
                "Why did the blind man fall into the well? Because he couldn’t see that well.",
                "I like dark humor… because the light ones make me sleepy.",
                "Why did the skeleton go to the party alone? He had no body to go with.",
                "I have a joke about zombies… but it’s a no-brainer.",
                "Why don’t graveyards ever get overcrowded? People are dying to get in.",
                "I used to have a handle on life… but it broke.",
                "Why did the old man fall in the well? Because he couldn’t see that well.",
                "I have a joke about lobotomy… but it’s a cut above the rest.",
                "Why don’t cannibals eat clowns? Because they taste funny.",
                "I have a joke about ghosts… but it’s a dead giveaway.",
                "I like my jokes like I like my coffee… black and bitter.",
                "Why did the chicken cross the playground? To get to the other slide.",
                "I have a joke about hanging… but it’s a bit of a stretch.",
                "Why did the vampire read the newspaper? He heard it had great circulation.",
                "I’d tell you a joke about graveyards… but it’s just lying there.",
                "I have a dark joke about surgery… but it might cut too deep.",
                "Why do graveyards have fences? Because people are dying to get in.",
                "I told my friend ten jokes to get him to laugh… sadly, no pun in ten did.",
                "I like my humor like my chocolate… dark.",
                "Why did the grim reaper get a promotion? He was outstanding in his field.",
                "I have a joke about funeral services… but it’s too dead on.",
                "Why did the ghost go to the bar? For the boos.",
                "I have a joke about death… it’s a killer.",
                "Why did the skeleton go to the barbecue? To get another rib.",
                "I have a dark joke about cannibalism… but it’s a bit meaty.",
                "Why did the old man fall in the well? Because he couldn’t see that well.",
                "I like my humor like I like my humor… dark and twisted.",
                "Why don’t graveyards ever get overcrowded? People are dying to get in.",
                "I have a joke about zombies… it’s deader than the punchline.",
                "Why did the coffin go to the party? Because it was dying to have fun.",
                "I have a joke about murder… but it’s a killer.",
                "Why did the murderer stay home? He wanted to keep a low profile.",
                "I have a joke about poisons… it’s a little toxic.",
                "Why do vampires always seem sick? They’re always coffin.",
                "I have a joke about the dark… but you might not get it.",
                "Why don’t graveyards ever get overcrowded? People are dying to get in.",
                "I have a joke about shadows… but it’s a bit shady.",
                "Why did the zombie go to school? He wanted to improve his deaducation.",
                "I have a joke about serial killers… it’s cutthroat.",
                "Why did the corpse cross the road? To prove he wasn’t chicken.",
                "I have a joke about funerals… it’s a dead giveaway.",
                "Why don’t skeletons fight each other? They don’t have the guts.",
                "I have a dark joke about vampires… it sucks.",
                "Why did the ghost go to school? To learn how to be transparent.",
                "I have a joke about hauntings… it will stick with you.",
                "Why did the grim reaper get fired? He couldn’t meet the deadlines.",
                "I have a joke about darkness… it’s too shady to share.",
                "Why did the skeleton go to the party alone? He had no body to go with.",
                "I have a joke about crypts… it’s tomb-ly hilarious.",
                "Why don’t graveyards ever get overcrowded? People are dying to get in.",
                "I have a joke about murder… it’s dead funny.",
                "Why did the ghost sit on the fence? He didn’t have a body to sit on.",
                "I have a joke about witches… it’s spellbinding.",
                "Why did the zombie go to the party? Because he had a brain to pick.",
                "I have a joke about dark humor… it’s light on sensitivity.",
                "Why did the vampire go to school? He wanted to improve his bite.",
                "I have a joke about coffins… it’s dead serious.",
                "Why did the old man fall in the well? Because he couldn’t see that well.",
                "I have a joke about cemeteries… it’s grave.",
                "Why did the skeleton go to the dance? Because he had no body to go with.",
                "I have a joke about ghosts… it’s hauntingly funny.",
                "Why did the zombie break up with his girlfriend? She found him too dead inside.",
                "I have a joke about vampires… it’s biting humor.",
                "Why did the grim reaper get promoted? He was outstanding in his field.",
                "I have a joke about death… it’s killer funny.",
                "Why did the skeleton stay home? He didn’t feel up to it.",
                "I have a joke about cemeteries… it’s in-tomb-icable.",
                "Why did the ghost go to therapy? He had too many haunting memories.",
                "I have a joke about darkness… it’s too deep to explain."
            ],
            "double_meaning": [
                "Why isn’t there a pregnant Barbie doll? Ken came in another box.",
                "Why did the snowman suddenly smile? He could see the snowblower coming.",
                "Why did the weatherman’s cheeks turn pink? He saw the climate change.",
                "What did Nala say to Simba in bed? Move fasta (Mufasa).",
                "What did Cinderella say to Prince Charming? “Want to see if it fits?”",
                "How did Burger King get Dairy Queen pregnant? He forgot to wrap his Whopper.",
                "Why are one-night stands with a man like earthquakes? You never know how long they’ll last.",
                "What’s the difference between a secret and lingerie? One is really hard to keep, while the other is difficult to take off.",
                "What does a sign on an out-of-business brothel say? Beat it, we’re closed.",
                "What did one traffic light say to the other? Look away, I’m changing!",
                "What’s long, hard and full of seamen? Submarines.",
                "How are push-up bras like bags of chips? When you open them, you realize they’re half empty.",
                "What do you call a cheap circumcision? A rip off.",
                "What’s the difference between a pregnant woman and a lightbulb? You can unscrew a lightbulb.",
                "My wife was really mad about the neighbor sunbathing nude outside. Personally, I’m on the fence.",
                "Did you hear about the guy who got a Viagra stuck in his throat? Yeah, he’s suffering from a stiff neck now.",
                "Did you hear about the proctologist whose girlfriend cheated on him? It totally rectum.",
                "What do you call a bra that you can’t take off? A booby trap.",
                "What do you get when you mix Viagra with spinach? Strong to the finish.",
                "How do you spot a blind person at a nude beach? It’s not hard.",
                "There’s a new Viagra and prune juice diet that’s out. Unfortunately, you can’t tell if you’re coming or going.",
                "Why do women like older men? They know how to stay up longer.",
                "What is the difference between light and hard? You can actually sleep with a light on.",
                "Why do men like love at first sight? It saves them a lot of time.",
                "What’s the difference between a golf ball and G-spot? A guy will actually search for a golf ball.",
                "Is that a mirror in your pocket? Because I can see myself in your pants.",
                "Which animal has the largest chest? A Z-bra.",
                "How does a wiener go camping? In a Wiener-bago.",
                "My wife asked me to spoon in bed, but I’d rather fork.",
                "What’s the difference between peanut butter and jam? Only one has nuts.",
                "What does the horny toad say? Rub it.",
                "What do you call a nanny with breast implants? A faux-pair.",
                "What does a hot dog use for protection? Condoments.",
                "What does a robot do after a one-night stand? He nuts and bolts.",
                "What is a long, wide thing that men carry? A tie.",
                "Who is Cogsworth’s best friend? His candlestick.",
                "What do you call an Italian hooker? A pasta-tute.",
                "What did Pongo and Perdita say after they did the deed? That hit the spot.",
                "Are you a pie? Because I’d like a piece of you.",
                "How did the police catch the naked man breaking into Zales? They grabbed him by the jewels.",
                "What’s the difference between a snowman and a snow woman? Snowballs.",
                "What did Winnie-the-Pooh say to his new love interest? Show me the honey.",
                "Want to hear a dirty joke? A white horse fell in a mud puddle. Want to hear a clean joke? The white horse took a bath.",
                "What gets wetter when things get steamy? Steamboats.",
                "What’s six inches long and has two nuts at the end? An Almond Joy.",
                "Why did the male chicken wear underwear on its head? Because its pecker was on its face.",
                "Can I watch TV? Yes, but don’t turn it on.",
                "Why did the ranch blush? He saw the salad dressing.",
                "What’s hot, pink and wet? A pig in a hot tub.",
                "Why couldn’t the lizard get a girlfriend? Because he had a reptile dysfunction.",
                "Why are men like popcorn? They satisfy you, but only for a little while.",
                "Why did the fish blush? It saw the ocean’s bottom.",
                "What kind of bees produce milk? Boo-bees.",
                "What’s the difference between ‘Oooh!’ and ‘Aaah!’? About three inches.",
                "What holds your buns firmly and makes them look round and pretty? A hair tie.",
                "What is Peter Pan’s favorite place to eat out? Wendy’s.",
                "Why did the mermaid wear seashells? She outgrew her b-shells.",
                "Why is a one-night stand with a man like a snowstorm? You never know how long it’ll last.",
                "A couple were snuggling, and his wife said softly, Speaking of fantasies, how about the one of you ironing?",
                "What do you play with at night that also vibrates? A cell phone.",
                "Why does it take 100 million sperm to fertilize one egg? Because they won’t stop to ask for directions.",
                "What’s in a man’s pants that you won’t find in a girl’s pants? Pockets.",
                "What did one boob say to the other boob? If we don’t get support, people will think we’re nuts.",
                "What did Cinderella do when she got to the ball? She gagged.",
                "What do you call a virgin on a waterbed? A cherry float.",
                "A cow has four, but a woman only has two. What am I? Legs.",
                "Why did the sperm cross the road? Because I put on the wrong sock this morning.",
                "What did Nala say to Simba? Hakuna my tatas.",
                "Do you work at Dick’s? Because you’re sporting the goods.",
                "Do you believe in karma? Because I know some Karma Sutra positions we can try.",
                "What’s the difference between a woman’s husband and her boyfriend? 60 minutes.",
                "Were your parents bakers? They should have been because you’ve got a nice set of buns.",
                "Is your car battery dead? Because I’d really like to jump you.",
                "Did you butt dial me? I swear your booty is calling me.",
                "Why did Popeye punch the Pope? He heard he went to Mount Olive.",
                "What’s the difference between a microwave and a woman? A man will actually press and pull a microwave’s buttons and knobs.",
                "Are you Little Caesars? Because I’m hot and I’m ready.",
                "Are you a Slytherin? I hope so, because I really want you to slither into my Chamber of Secrets.",
                "What’s the difference between you and an egg? An egg gets laid.",
                "Are you a trampoline? Because I’d really like to bounce on you.",
                "Are you a sea lion? Because I can see you lion in my bed tonight.",
                "What did the hurricane say to the coconut tree? Hold on to your nuts.",
                "What did the toaster say to the slice of bread? I want you inside me.",
                "Are you a firefighter? Because you make me hot and leave me wet.",
                "Wanna know something about Pinocchio? His nose isn’t the only piece of wood that grows.",
                "What do you call a horny cow? Beef jerky.",
                "Why did the squirrel swim on its back? To keep its nuts dry.",
                "I can be short or long, and women usually demand my full attention. What am I? A conversation.",
                "Are you a light switch? Because you turn me on.",
                "What’s two inches wide, six inches long and makes everyone go crazy? A $100 bill.",
                "Are you my homework? Because I’m not doing you when I definitely should be.",
                "What is furry and peeking out of your pajamas at night? A person’s head.",
                "Are you a Rubik’s Cube? Because the more I play with you, the harder you get.",
                "What’s made of rubber, handed out at some schools and exists to prevent mistakes? Erasers."
            ]
        }
