FLIRTY_ROASTS = [
            "You’re too cute… it’s unfair to the rest of us.",
            "Stop being this adorable… I can’t focus!",
            "Careful, your smile is dangerous for my heart ❤️",
            "You’re giving me reasons to write poetry about you 😏",
            "If charm were a crime, you’d be serving life.",
            "You’re like a magnet… I can’t stay away.",
            "Why do you have to look this good all the time?",
            "Your cuteness should be illegal.",
            "You make it impossible to think straight.",
            "You’re the reason I check my phone too much.",
            "How are you always this flawless?",
            "You have a way of breaking hearts… mine included.",
            "Stop stealing the spotlight with that smile.",
            "You make everyone else look ordinary.",
            "You should come with a warning label: dangerously charming.",
            "I didn’t know perfection had a face.",
            "Your laugh should be trademarked.",
            "You’re like caffeine… addictive and essential.",
            "You make simple things look extraordinary.",
            "How is it possible to be this mesmerizing?",
            "You’re my favorite distraction.",
            "Your energy is way too captivating.",
            "You’re like a plot twist in my day.",
            "I can’t decide if I want to stare or smile.",
            "Your eyes should come with a pause button.",
            "You have the kind of charm that ruins focus.",
            "Even silence around you feels interesting.",
            "You’re a masterpiece in motion.",
            "How is it legal to be this cute?",
            "You have the magic to make ordinary moments unforgettable.",
            "You could make a storm feel like a sunny day.",
            "Your presence is like a caffeine hit for the soul.",
            "You’re too charming for your own good.",
            "I think my heart skipped a beat just now.",
            "You have that dangerous mix of smart and stunning.",
            "Stop being so effortlessly captivating.",
            "You’re like a distraction I actually enjoy.",
            "You make me forget what I was doing.",
            "Your smile should have its own fan club.",
            "You’re the reason my thoughts are in chaos.",
            "You’re a walking heartbreaker, in the cutest way.",
            "Every glance feels like a reward.",
            "You make everyday moments feel magical.",
            "You have that effortless allure everyone notices.",
            "You could make a library feel like a party.",
            "Your vibe is dangerously charming.",
            "You’re the kind of trouble I don’t want to avoid.",
            "You make the ordinary seem extraordinary.",
            "I didn’t know someone could be this engaging.",
            "You’re a puzzle I don’t want solved.",
            "You make the world feel more interesting.",
            "Your style should come with a warning.",
            "You’re too magnetic for your own good.",
            "You make my heart skip like a scratched CD.",
            "Your aura is dangerously intoxicating.",
            "I can’t get over how captivating you are.",
            "You turn simple conversations into adventures.",
            "You have a mischievous charm I can’t resist.",
            "Your presence lights up the room.",
            "You’re the kind of distraction I chase.",
            "You could make math feel romantic.",
            "You have that effortless sparkle.",
            "Even your silence is alluring.",
            "You’re the highlight of my day.",
            "You’re dangerously attractive, but I’m willing to risk it.",
            "Your laugh is my new favorite sound.",
            "You make focus impossible… in the best way.",
            "You’re like sunshine in human form.",
            "You make chaos feel like comfort.",
            "Your charm is criminally effective.",
            "You’re the kind of trouble that feels right.",
            "You’re like a magnet… impossible to ignore.",
            "I can’t decide if I should run or stay.",
            "You have that rare kind of beauty that feels personal.",
            "You make hearts race without trying.",
            "You’re a little dangerous, and I like it.",
            "Your energy is addictive.",
            "You could make a museum feel alive.",
            "You’re the kind of distraction I enjoy too much.",
            "You make ordinary moments unforgettable.",
            "Your smile could start a revolution.",
            "You’re the highlight of every room.",
            "You have a charm that should be illegal.",
            "Even your smallest gestures captivate me.",
            "You make everything feel lighter.",
            "You’re dangerously irresistible.",
            "You’re the kind of person everyone notices.",
            "You make ordinary things exciting.",
            "Your presence is a gift and a temptation.",
            "You make the world feel softer and warmer.",
            "You have the kind of aura that draws people in.",
            "Even your frowns are oddly captivating.",
            "You’re like a riddle I never want to solve.",
            "You make every glance count.",
            "You’re a master at stealing attention.",
            "Your charm is effortless and magnetic.",
            "You could make the rain feel romantic.",
            "You’re the kind of trouble I’d chase forever.",
            "You make mundane days feel extraordinary.",
            "Your confidence is mesmerizing.",
            "You’re a spark I can’t ignore.",
            "Even when quiet, you command attention.",
            "You make hearts flutter without trying.",
            "You’re the kind of enigma I want to unravel.",
            "You make time feel faster just by being here.",
            "You’re captivating in every possible way.",
            "Your vibe is addictive, and I’m hooked.",
            "You make every moment feel alive."
        ]

GENERAL_ROASTS = [
    "You have the confidence of someone who has no idea what's going on.",
    "You're not stupid; you just have bad luck thinking.",
    "If laziness were an Olympic sport, you'd come second… because you wouldn’t finish.",
    "You don’t need a GPS — you’re already lost.",
    "You bring everyone so much joy… when you leave.",
    "Your secrets are safe with me. I never even listen when you tell me them.",
    "You have something on your chin… no, the third one down.",
    "You bring everyone together… like a magnet… for disaster.",
    "You have something I like… oh yes, nothing.",
    "Your sense of direction is amazing… if getting lost was an art.",
    "You're proof that even evolution can take a break sometimes.",
    "You have an impeccable talent for being underwhelming.",
    "If brains were taxed, you’d get a refund.",
    "You're like a cloud… when you disappear, it’s a beautiful day.",
    "You're as sharp as a marble.",
    "You have the charm of a damp sock.",
    "You're the human equivalent of a participation award.",
    "Your secrets are safe… mostly because I forget them instantly.",
    "You have the energy of a sloth on vacation.",
    "You're like a software update… unnecessary and annoying.",
    "You have the face for radio and the voice for print.",
    "You're living proof that mistakes can be permanent.",
    "You could be the poster child for mediocrity.",
    "Your vibe is ‘meh’ but consistent.",
    "You have a mind like a steel trap… rusted shut.",
    "You're as bright as a black hole.",
    "You’re proof that even nature has a sense of humor.",
    "You have all the grace of a giraffe on roller skates.",
    "Your confidence is inspiring…ly misguided.",
    "You’re like a cloud of confusion.",
    "You're the reason some animals eat their young.",
    "You bring new meaning to the phrase ‘awkward moment’.",
    "Your logic is… creative.",
    "You have the charisma of expired milk.",
    "You’re like a software bug — persistent and irritating.",
    "You could win an award… for doing the bare minimum.",
    "You're like a puzzle… but all the pieces are squares.",
    "Your secrets are safe with me… mostly because I don’t care.",
    "You have the subtlety of a brick.",
    "You make chaos feel normal.",
    "You’re like a broken pencil… pointless.",
    "You have the charm of a wet mop.",
    "Your wit is… somewhere in development.",
    "You're the human embodiment of ‘oops’.",
    "You have the consistency of spoiled milk.",
    "You’re the reason instructions exist.",
    "Your brain is a work in progress… and it's taking a long time.",
    "You're like a cloud… but gray, and always raining on my plans.",
    "Your energy is… unique.",
    "You have all the poise of a startled cat.",
    "You could be a motivational poster… about what not to do.",
    "You're like a Wi-Fi signal… weak and unreliable.",
    "Your sense of timing is impeccable… if you like missing everything.",
    "You're a human ‘under construction’ sign.",
    "You have the subtlety of a foghorn.",
    "You’re living proof that life isn’t fair.",
    "Your ideas are… interestingly wrong.",
    "You're like a broken clock… right twice a day.",
    "Your sense of style is… avant-garde, if confusing.",
    "You have the attention span of a goldfish.",
    "You're like a keyboard with missing keys.",
    "You bring excitement… like a power outage.",
    "You have the patience of a hungry lion… barely.",
    "You're like a GPS that constantly recalculates… and gets lost anyway.",
    "You have all the elegance of a brick wall.",
    "Your confidence is… something else.",
    "You’re like a soda left open… flat and sad.",
    "You have a face that could stop a clock… permanently.",
    "You bring the fun… in small, disappointing doses.",
    "Your logic is as twisted as spaghetti.",
    "You could be a cautionary tale.",
    "You're the reason some myths exist.",
    "You have the charm of a parking ticket.",
    "You're like a candle… dim and easily blown out.",
    "Your energy is… occasionally noticeable.",
    "You're as subtle as a marching band.",
    "You have the grace of a tumbleweed.",
    "You're like a joke without a punchline.",
    "Your humor is… a work in progress.",
    "You’re a limited edition… mostly because nobody wants another.",
    "You have the intelligence of a calculator… unplugged.",
    "You're like a flat tire… a drag on everything.",
    "You bring color… mostly gray.",
    "Your ideas have… potential… if it was 200 years ago.",
    "You're like a phone with no signal.",
    "You have all the charm of an empty room.",
    "You could be a tutorial on what not to do.",
    "You're the human equivalent of background noise.",
    "Your wit is… under construction.",
    "You're like a cup of decaf… disappointing.",
    "You have the coordination of a newborn deer.",
    "You're like a puzzle with pieces missing.",
    "Your energy is optional… like a free trial.",
    "You're as unpredictable as a broken metronome.",
    "You bring excitement… like lukewarm water.",
    "Your presence is… memorable in an unforgettable way.",
    "You're like a shadow… following but never leading.",
    "Your subtlety is… non-existent.",
    "You’re like a pop quiz… nobody asked for it.",
    "You have the speed of a slow internet connection.",
    "You're like a book with blank pages.",
    "Your charm is… slightly used.",
    "You're the reason instructions exist… again.",
    "You bring attention… unintentionally.",
    "Your ideas are… charmingly off-target.",
    "You have all the elegance of spilled coffee.",
    "You're like a cloud… mostly gray, sometimes confusing."
]
